version: "3.7"
services:
  test-db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=moraki_test
      - POSTGRES_USER=moraki_app
      - POSTGRES_PASSWORD=moraki_app